### ISSUE TITLE
Database Schema 설계

### ISSUE THREAD

**Issue by jungcome7** [woowa-techcamp-2020/hkb-9#1]

**Comment by jungcome7** [comment]
# ERD

![image](https://user-images.githubusercontent.com/34447105/88762997-4d05e200-d1ad-11ea-877a-0b6081d7c818.png)

# 😑 user

| id            | INT, PRIMARY KEY, AUTO_INCREMENT, NOT NULL |
| :------------ | ------------------------------------------ |
| login_id      | VARCHAR(20), NOT NULL                      |
| password      | VARCHAR(100), NOT NULL                     |
| salt          | VARCHAR(100), NOT NULL                     |
| refresh_token | VARCHAR(100), NOT NULL                     |


<br/>

# 😡 card

| user_id | INT, FOREIGN KEY, NOT NULL |
| :------ | -------------------------- |
| name    | VARCHAR(20), NOT NULL      |


<br/>

# 😎 account

| id           | INT, PRIMARY KEY, AUTO_INCREMENT, NOT NULL                   |
| :----------- | ------------------------------------------------------------ |
| type         | enum('income', 'expense') , NOT NULL                         |
| category     | enum('salary', 'pocket', 'extra', 'food', 'living', 'shopping', 'transportation', 'health', 'culture', 'unclassified') |
| amount       | INT, NOT NULL                                                |
| content      | VARCHAR(255), NOT NULL                                       |
| month        | INT, NOT NULL                                                |
| payment_date | DATETIME                                                     |
| user_id      | INT, FOREIGN KEY, NOT NULL                                   |

**Comment by doonguk** [comment]
![image](https://user-images.githubusercontent.com/39187116/88764337-be469480-d1af-11ea-8f48-2186a9bab698.png)
