### ISSUE TITLE
ERD 제작

### ISSUE THREAD

**Issue by jungcome7** [woowa-techcamp-2020/hkb-9#2]

**Comment by jungcome7** [comment]
![image](https://user-images.githubusercontent.com/34447105/88762997-4d05e200-d1ad-11ea-877a-0b6081d7c818.png)

**Comment by doonguk** [comment]
![image](https://user-images.githubusercontent.com/39187116/88764422-e3d39e00-d1af-11ea-883a-e90279642a4a.png)
