### ISSUE TITLE
1주차 마일스톤(~7/28) 스터디

### ISSUE THREAD

**Issue by jungcome7** [woowa-techcamp-2020/hkb-9#5]
## 요약
1. 프론트엔드 Model & View(Observer 패턴) 학습
2. EC2 자동 배포 학습

## 투두리스트
- [x] 1번 Bong
- [x] 2번 Hong

**Comment by jungcome7** [comment]
1. 프론트엔드 View & Model에 관한 루카스 강의자료를 보고 공부했습니다. 옵저버 패턴에 대한 대강의 이해가 생겼습니다. 그러나 아직 실제 어떤 상황에서 패턴을 적용해야 하는지 감이 오질 않습니다. 앞으로 프론트 코드를 쌓아가면서 적용할 수 있는 방법을 고민해봐야 할듯합니다. 프로젝트 중반 이후 다시 한번 공부할 예정입니다.

**Comment by doonguk** [comment]
2. 자동 배포학습은 하지 못했습니다. 우선순위가 낮은 것 같아서 '자동 배포학습' 대신 'VanilaJS로 캘린더' 만들기를 진행했습니다.  자동 배포 부분은 API 작업 시작할 때 다시 학습해보는게 좋을 것 같습니다..!

**Comment by jungcome7** [comment]
![image](https://user-images.githubusercontent.com/34447105/88755675-a4e81d00-d19c-11ea-96f8-6339e0cf675a.png)
![image](https://user-images.githubusercontent.com/34447105/88755690-aca7c180-d19c-11ea-9d87-ecc618158275.png)
